-- Non–Excel reference data (interest dictionary, feature flags, etc.) can go here.
-- Societies + activities from the Rubric workbook are generated into ./seeds/from_xlsx.sql.
-- Generate that file with:  python scripts/build_seed_from_xlsx.py [path-to-xlsx]
